name: reactive_widgets
description: A set of widgets to make it more easier to build reactive interfaces.
version: 0.5.1
author: Pedro Bissonho <pedro.bissonho@gmail.com>
homepage: https://github.com/PedroBissonho/reactive-widgets

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
